### ISSUE TITLE
ReadLVar is possible?

### ISSUE THREAD

**Issue by MMontalto** [tcavenezuela/fsuipc.js#15]
Hi, I'm not an expert, but I'm trying to interface with some 3rd party Sim plugins. Unfortunately looking on the internet I found that it is necessary to read the LVAR, but to do so it's necessary at the moment a wasm module. I saw that FSUIPC has one already built into the installation.
I have not found any info about it in this repo, is it already implemented or is it possible to implant the reading of the local variables in the future? Thanks in advance!

**Comment by carl0shd** [comment]
> Hi, I'm not an expert, but I'm trying to interface with some 3rd party Sim plugins. Unfortunately looking on the internet I found that it is necessary to read the LVAR, but to do so it's necessary at the moment a wasm module. I saw that FSUIPC has one already built into the installation. I have not found any info about it in this repo, is it already implemented or is it possible to implant the reading of the local variables in the future? Thanks in advance!

Hi @MMontalto sorry for the late response. At the moment this library doesn't support reading LVAR from MSFS but its possible to add the support in the future, unfortunately i dont have the time to research and implement this 😔.
